import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'

// Base path is '/' because we deploy to a custom domain (tickpedia.com).
// If we ever fall back to project pages, set base to '/<repo-name>/'.
//
// `@/beam` resolves to the generated SemiLayer client at the repo root
// (gitignored, regenerated by `pnpm semilayer:generate`).
export default defineConfig({
  plugins: [react()],
  base: '/',
  server: { port: 5173 },
  resolve: {
    alias: {
      '@/beam': resolve(import.meta.dirname, '..', '..', 'generated', 'semilayer'),
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
  // Read .env from the repo root (one .env, all apps share it).
  envDir: resolve(import.meta.dirname, '..', '..'),
  // Allow NEXT_PUBLIC_* alongside VITE_* so admin and web read the same keys.
  envPrefix: ['VITE_', 'NEXT_PUBLIC_'],
})
